trigger:
  branches:
    include:
    - release/*
    - hotfix/*
    - develop
    - master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps: 
    - task: PowerShell@2
      displayName: Build Script
      inputs:
        targetType: 'filePath'
        filePath: 'build-docker-containers.ps1'
        pwsh: true
    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
        failTaskOnFailedTests: true